# Generated by Django 2.2.6 on 2019-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
