# Generated by Django 2.2.5 on 2019-10-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_entradas_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entradas',
            new_name='Tickets',
        ),
    ]
