# Generated by Django 2.2.5 on 2019-11-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_auto_20191021_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistas',
            options={'ordering': ['nombre', 'nacionalidad']},
        ),
        
    ]
