# Generated by Django 2.2.5 on 2019-11-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_auto_20191103_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistas',
            name='genero',
        ),
        migrations.AddField(
            model_name='artistas',
            name='genero',
            field=models.ManyToManyField(to='entradas.Genero'),
        ),
    ]
