# Generated by Django 2.2.5 on 2019-11-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_auto_20191103_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
