# Generated by Django 2.2.5 on 2019-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0007_auto_20191104_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
