# Generated by Django 2.2.5 on 2019-11-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0009_auto_20191106_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistas',
            old_name='genero',
            new_name='gen',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='nomg',
        ),
    ]
