# Generated by Django 2.2.5 on 2019-11-08 02:58

from django.db import migrations, models
import entradas.models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0011_auto_20191107_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='gen',
            field=models.CharField(default='', max_length=200, verbose_name=entradas.models.Genero),
        ),
    ]
