# Generated by Django 2.2.5 on 2019-11-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0012_auto_20191107_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistas',
            name='gen',
        ),
        migrations.AddField(
            model_name='artistas',
            name='gen',
            field=models.ManyToManyField(to='entradas.Genero'),
        ),
    ]
