# Generated by Django 2.2.5 on 2019-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0013_auto_20191107_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistas',
            options={'ordering': ['nombre', 'nacionalidad']},
        ),
        migrations.AddField(
            model_name='artistas',
            name='nacionalidad',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistas',
            name='fundacion',
            field=models.DateField(null=True),
        ),
    ]
